Change terminology for i.a. Services
SURFscz/SBS pull request #1561
Opened 2024-08-30 05:31 UTC by oharsta

2024-09-02 13:53 UTC, logan-life commented on client/src/locale/en.js
> +            noEntities: "There are no application configured with the mock SCIM endpoint",
applications

2024-09-02 13:56 UTC, logan-life commented on client/src/locale/en.js
> +        accepted_user_policyTooltip: "An acceptable use policy (AUP) is a document stipulating constraints and practices that a user must agree to for access to an application or system.",
let's standardize the capitalization of Privacy Policy and Acceptable Use Policy here (dealer's choice)

2024-09-02 13:58 UTC, logan-life commented on client/src/locale/en.js
> +            confirmation: "Resetting the AUP will require all user of this application '{{name}}' to accept its AUP again. Do you want that?",
users

2024-09-02 14:01 UTC, logan-life commented on client/src/locale/en.js
> +        membershipExpiryDateTooltip: "The expiration date of the membership, after which the user cannot log in to applications connected to this collaboration.",
maybe a good chance to standardize on "cannot" vs "can not". 

Mostly we are using "can not" which is a little awkward to me, but if it is the preferred way that's okay too.

2024-09-02 14:02 UTC, logan-life commented on client/src/locale/en.js
> +        serviceConnectionRequests: "Application connection Requests",
Application connection requests? Application Connection Requests?

2024-09-02 14:03 UTC, logan-life commented on client/src/locale/en.js
> +        title: "Applications for application {{name}}",
Is this supposed to be 

Applications for organisation {{name}}?

2024-09-02 14:04 UTC, logan-life commented on client/src/locale/en.js
> +        noAccessAllowed: "This application cannot be enabled for all collaborations, because none collaborations can connect.",
because no collaborations can connect

2024-09-02 14:05 UTC, logan-life commented on client/src/locale/en.js
> +        shortNameTooltip: "A application group's short name will be used (1) for groups provisioned to collaborations, prepended by short name of the application and separated by a hyphen '-' and (2)
An

2024-09-02 14:05 UTC, logan-life commented on client/src/locale/en.js
> +        shortNameTooltip: "A application group's short name will be used (1) for groups provisioned to collaborations, prepended by short name of the application and separated by a hyphen '-' and (2)
extra period

2024-09-02 14:07 UTC, logan-life commented on client/src/locale/en.js
> +            singleInfo: "A application used by this collaboration requires that you agree to their acceptable use policy.",
An

2024-09-02 14:08 UTC, logan-life commented on client/src/locale/en.js
>      serviceConnectionRequest: {
Application Connection request? Application Connect request?

2024-09-02 14:08 UTC, logan-life commented on client/src/locale/en.js
> +            accepted: "Application Connect request for application {{name}} was accepted",
Application Connection request? Application connection request?

2024-09-03 07:11 UTC, logan-life commented on client/src/locale/en.js
> +        serviceConnectionRequests: "Application connection Requests",
Also see above use of "application connect request" 

let's standardize on one

2024-09-03 07:38 UTC, logan-life commented on client/src/locale/en.js
> +            noEntities: "There are no application configured with the mock SCIM endpoint",
```suggestion
            noEntities: "There are no applications configured with the mock SCIM endpoint",
```

2024-09-03 08:19 UTC, logan-life requested changes

2024-09-03 08:19 UTC, logan-life commented on client/src/locale/nl.js
> +        runOpenRequestsInfo: "Run the weekly cron job to report all open requests for CO, Org and application admins",
```suggestion
        runOpenRequestsInfo: "Run the weekly cron job to report all open requests for CO, Org and Application admins",
```

2024-09-03 08:19 UTC, logan-life commented on client/src/locale/nl.js
> +                "Configure a applicatie with the following SCIM URL to start testing the SCIM functionality",
```suggestion
                "Configure an application with the following SCIM URL to start testing the SCIM functionality",
```

2024-09-03 08:19 UTC, logan-life commented on client/src/locale/nl.js
> +        serviceManager: "applicatiemanager",
```suggestion
        serviceAdmin: "Applicatiebeheerder",
        serviceManager: "Applicatiemanager",
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_expired_notification.html
> +        to login again on the applications of this collaboration.</p>
```suggestion
        to login again to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_expired_notification.txt
> +        to login again on the applications of this collaboration.
```suggestion
        to login again to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_expires_warning.html
> +        can not login anymore on the applications of this collaboration.</p>
```suggestion
        can not login anymore to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_expires_warning.txt
> +        can not login anymore on the applications of this collaboration.
```suggestion
        can not login anymore to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_suspensed_notification.html
> +        to login again on the applications of this collaboration.</p>
```suggestion
        to login again to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_suspensed_notification.txt
> +        to login again on the applications of this collaboration.
```suggestion
        to login again to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_suspension_warning.html
> +        to login again on the applications of this collaboration.</p>
```suggestion
        to login again to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/collaboration_suspension_warning.txt
> +        to login again on the applications of this collaboration.
```suggestion
        to login again to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/membership_expired_notification.html
> +        login again on the applications of this collaboration.</p>
```suggestion
        login again to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/membership_expired_notification.txt
> +    login again on the applications of this collaboration.
```suggestion
    login again to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/membership_expires_warning.html
> +        can not login anymore on the applications of this collaboration.</p>
```suggestion
        can not login anymore to the applications of this collaboration.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/membership_expires_warning.txt
> +can not login anymore on the applications of this collaboration.
```suggestion
can not login anymore to the applications of this collaboration.
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request.html
> +{% block title %}SURF application Connection request{% endblock %}
```suggestion
{% block title %}SURF application connection request{% endblock %}
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request.txt
> +{% block title %}SURF application Connection request{% endblock %}
```suggestion
{% block title %}SURF application connection request{% endblock %}
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request_declined.html
> +        Denied connection application request
```suggestion
        Declined connection application request
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request_declined.html
> +        Your connection application request for application {{ service.name }} is denied.</p>
```suggestion
        Your connection application request for application {{ service.name }} is declined.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request_org.html
> +{% block title %}SURF application Connection request{% endblock %}
```suggestion
{% block title %}SURF application connection request{% endblock %}
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_connection_request_org.txt
> +{% block title %}SURF application Connection request{% endblock %}
```suggestion
{% block title %}SURF application connection request{% endblock %}
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_request_declined.html
> +        Denied application request
```suggestion
        Declined application request
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_request_declined.html
> +        Your request for application {{ service.name }} is denied.</p>
```suggestion
        Your request for application {{ service.name }} is declined.</p>
```

2024-09-03 08:19 UTC, logan-life commented on server/templates/service_request_declined.html
>      <p>The reason for the denialis:</p>
```suggestion
    <p>The reason is:</p>
```

2024-09-05 13:04 UTC, FlorisFokkinga commented on client/src/locale/nl.js
> +        serviceManager: "applicatiemanager",
Original isn't capitalized.

2024-09-05 13:07 UTC, FlorisFokkinga commented on client/src/locale/nl.js
> +            noEntities: "There are no applications configured with the mock SCIM endpoint",
Yes, but it's only for platform admins.

2024-09-05 13:08 UTC, FlorisFokkinga commented on client/src/locale/en.js
> +        subTitle: "To access application {{name}} you will have to be provisioned. This unfortunately takes some time, grab a cup of ☕️.",
I don't think it's used.

2024-09-05 13:10 UTC, FlorisFokkinga commented on client/src/locale/en.js
> +        infoJoinRequest: " Before you can request to join this collaboration, you must review the acceptable use policy (AUP) and privacy policy of the application. Indicate below whether you accept
Dutch has a starting space as well. Not sure if it's there for a reason.

2024-09-05 13:19 UTC, FlorisFokkinga commented on client/src/locale/en.js
> +        accepted_user_policyTooltip: "An acceptable use policy (AUP) is a document stipulating constraints and practices that a user must agree to for access to an application or system.",
Done.

2024-09-05 13:27 UTC, logan-life reviewed
LGTM

2024-09-05 13:30 UTC, merged